name: Generate player comments

on:
  workflow_dispatch:
  push:
    paths:
      - "data/players.csv"
      - "generate_comments.py"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run generator
        run: |
          python generate_comments.py --in data/players.csv --out data/players.csv --overwrite
      - name: Commit updated players.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/players.csv
          git commit -m "auto: add/update comments" || echo "no changes"
          git push
