name: Auto Generate AI comments for players.csv

on:
  schedule:
    # 毎日午前3時（日本時間）に自動実行
    - cron: '0 18 * * 1'
  workflow_dispatch:
  push:
    paths:
      - "data/players.csv"
      - "scripts/generate_comments.py"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run generator
        run: |
          python scripts/generate_comments.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/players.csv || true
          git commit -m "auto: update players.csv with AI comments" || echo "no changes"
          git push
